// Tile maps for the Mario-like platformer. One char per tile (rows padded on parse).
// Legend: X ground · B brick · ? coin-block · M power-up block · S star block · o coin
//         g goomba · k koopa · p pipe · = platform · F flag · @ start · (space) empty
export const LEVELS: string[][] = [
  // 1 — basics: gentle gaps, intro goombas, ? blocks, one pipe
  [
    '                                                                        ',
    '                                                                        ',
    '                                                                        ',
    '                  ?                                                      ',
    '                                          o o o                         ',
    '         o o      ?  M   ?                                              F',
    '                                       =====               o o o       X',
    '                            o o                                        X',
    '            =====                        ?      o o o     =====        X',
    '   @                  g          g            BB?BB              g     X',
    '          B?B        XX       p              XX        p              XX',
    '          XXX        XX       pp     g       XX        pp     g       XX',
    'XXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXX  XXXXXXXXXXXXXXX  XXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXX  XXXXXXXXXXXXXXX  XXXXXXXXXXXX',
  ],
  // 2 — pipes & goombas, taller pipes, more gaps
  [
    '                                                                            ',
    '                                                                            ',
    '              ?   M                              o o o                       ',
    '                              o o                                            ',
    '         o o            ?  B  ?         ====         B B B B               F',
    '                                                                          X ',
    '     =====        g          g       o o      g       ?        ===== g   X ',
    '              p       p          ppp        ppp              ppp         X ',
    '   @          pp      pp     g   ppp        ppp     g        ppp    g    X ',
    '       g      pp      pp         ppp        ppp              ppp        XX ',
    '      BBB     pp      pp         ppp        ppp     B?B      ppp        XX ',
    'XXXXXXXXXXXXXXXXX   XXXXXXXXXX  XXXXXXX   XXXXXXXXXXXXXXX  XXXXXX   XXXXXXX ',
    'XXXXXXXXXXXXXXXXX   XXXXXXXXXX  XXXXXXX   XXXXXXXXXXXXXXX  XXXXXX   XXXXXXX ',
    'XXXXXXXXXXXXXXXXX   XXXXXXXXXX  XXXXXXX   XXXXXXXXXXXXXXX  XXXXXX   XXXXXXX ',
  ],
  // 3 — "underground": low ceiling, koopas, coin rooms, star
  [
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'X                                                                      X',
    'X  o o o       BBBBB       o o o o       S        BBBB        o o o     X',
    'X            B     B                  BBBBBB                            X',
    'X  @     k    B  o  B    k        o o            k        ?  ?  ?       FX',
    'X       XX    BBBBB     XX    BBBB      ====    XX                     XX',
    'X      XXX             XXX                     XXX        k          XXXX',
    'X     o o o      k          ?  ?       o o o          BBB      o o   XXXX',
    'X              XXXX       XXXXX               =====          XX     XXXXX',
    'X     BBB                          k                  k            XXXXXX',
    'X    XXXXX     g       o o o      XXXX      g       XXXX     g     XXXXXXX',
    'X  XXXXXXXXX  XXXXX   XXXXXXXX   XXXXXXX  XXXXXXX  XXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  ],
  // 4 — precision platforming over pits, floating platforms, fire flower
  [
    '                                                                            ',
    '                                  o o o                                      ',
    '            M          ?                       o o o                        ',
    '        o o        =====       =====                      ?  ?             F',
    '                                            =====      =====              X ',
    '   @       =====                  o o                            g       X ',
    '        g          o o      g              =====      g    =====         X ',
    '      =====     =====    =====                     =====           ==== XX ',
    '                                  k          o o                       XX ',
    '                      g                    =====      g              XXXX ',
    '     ===            =====       ====                       ====     XXXXX ',
    'XXXXXX      XX            XX            XX           XX          XXXXXXXXX ',
    'XXXXXX      XX            XX            XX           XX          XXXXXXXXX ',
    '      ......      ......        ......        ......       .....          ',
  ],
  // 5 — gauntlet: everything + star to finish strong
  [
    '                                                                                ',
    '          ?  M  ?                          S                                     ',
    '                        o o o o                       B B B B                    ',
    '      o o        BBBB                 =====                        o o o        F',
    '                              g                    g                            X',
    '   @      =====      g            B?B        g           ====      g    k      X',
    '       g         k         ppp           ppp        k         ppp          g   X',
    '      BBB        pp        ppp     g     ppp       pp         ppp    g     XX   X',
    '     XXXXX  g    pp        ppp           ppp       pp   g     ppp         XXX  XX',
    '   XXXXXXXXXXX   pp    g   ppp    g      ppp       pp        ppp     k   XXXXXXXX',
    '  XXXXXXXXXXXXX XXXX      XXXXX        XXXXXXX   XXXXXX     XXXXXX       XXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXX   XXXXXXXXX   XXXXXXXXXX XXXXXXXXX  XXXXXXXXXX  XXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXX   XXXXXXXXX   XXXXXXXXXX XXXXXXXXX  XXXXXXXXXX  XXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXX   XXXXXXXXX   XXXXXXXXXX XXXXXXXXX  XXXXXXXXXX  XXXXXXXXXXXX',
  ],
]
