// Tile maps for the Mario-like platformer. One char per tile (rows padded on parse).
// Legend: X ground · B brick · ? coin-block · M power-up block · S star block · o coin
//         g goomba · k koopa · p pipe · = platform · F flag · @ start · (space) empty
export const LEVELS: string[][] = [
  // 1 — basics: gentle gaps, intro goombas, ? blocks, one pipe
  [
    '                                                                        ',
    '                                                                        ',
    '                                                                        ',
    '                  ?                                                      ',
    '                                          o o o                         ',
    '         o o      M  M   ?                                              F',
    '                                       =====               o o o       X',
    '                            o o                                        X',
    '            =====                        ?      o o o     =====        X',
    '   @                  g          g            BB?BB              g     X',
    '          B?B        XX       p              XX        p              XX',
    '          XXX        XX       pp     g       XX        pp     g       XX',
    'XXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXX  XXXXXXXXXXXXXXX  XXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXX  XXXXXXXXXXXXXXX  XXXXXXXXXXXX',
  ],
  // 2 — pipes & goombas, taller pipes, more gaps
  [
    '                                                                            ',
    '                                                                            ',
    '              ?   M                              o o o                       ',
    '                              o o                                            ',
    '         o o            ?  B  ?         ====         B B B B               F',
    '                                                                          X ',
    '     =====        g          g       o o      g       ?        ===== g   X ',
    '              W       p          ppp        ppp              ppp         X ',
    '   @          pp      pp     g   ppp        ppp     g        ppp    g    X ',
    '       g      pp      pp         ppp        ppp              ppp        XX ',
    '      BBB     pp      pp         ppp        ppp     B?B      ppp        XX ',
    'XXXXXXXXXXXXXXXXX   XXXXXXXXXX  XXXXXXX   XXXXXXXXXXXXXXX  XXXXXX   XXXXXXX ',
    'XXXXXXXXXXXXXXXXX   XXXXXXXXXX  XXXXXXX   XXXXXXXXXXXXXXX  XXXXXX   XXXXXXX ',
    'XXXXXXXXXXXXXXXXX   XXXXXXXXXX  XXXXXXX   XXXXXXXXXXXXXXX  XXXXXX   XXXXXXX ',
  ],
  // 3 — "underground": low ceiling, koopas, coin rooms, star
  [
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'X                                                                      X',
    'X  o o o      BBB?BBB         S             o o o o                     X',
    'X                                                                      X',
    'X      k         o o          M     M        ?  ?                      X',
    'X   BBBB          ====            BBBB             ====                 X',
    'X                                                                      X',
    'X     o o o          k           o o o           o o o                 X',
    'X   =====          =====            =====           =====              X',
    'X                                                                      X',
    'X@        g              k                        g         ^         FX',
    'XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  ],
  // 4 — precision platforming over pits, floating platforms, fire flower
  [
    '                                                                            ',
    '                                  o o o                                      ',
    '            M          ?                       o o o                        ',
    '        o o        ttttt       =====                      ?  ?             F',
    '                                            =====      =====              X ',
    '   @       H                      o o                            g       X ',
    '        g          o o      g              =====      g    =====         X ',
    '      D         =====    =====                     =====           ==== XX ',
    '                                  k          o o                       XX ',
    '                      g                    =====      g              XXXX ',
    '     s==            =====       ====                       ====     XXXXX ',
    'XXXXXX      XX            XX            XX           XX          XXXXXXXXX ',
    'XXXXXX      XX            XX            XX           XX          XXXXXXXXX ',
    '      LLLLLL      LLLLLL        LLLLLL        LLLLLL       LLLLL          ',
  ],
  // 5 — gauntlet: everything + star to finish strong
  [
    '                                                                                ',
    '          ?  M  ?                          S                                     ',
    '                        o o o o                       B B B B                    ',
    '      o o        BBBB                 =====                        o o o        F',
    '                              g                    g                            X',
    '   @      =====      g            B?B        g           ====      g    k      X',
    '       g         k         ppp           ppp        k         ppp          g   X',
    '      BBB        pp        ppp     g     ppp       pp         ppp    g     XX   X',
    '     XXXXX  g    pp        ppp           ppp       pp   g     ppp         XXX  XX',
    '   XXXXXXXXXXX   pp    g   ppp    g      ppp       pp        ppp     k   XXXXXXXX',
    '  XXXXXXXXXXXXX XXXX      XXXXX        XXXXXXX   XXXXXX     XXXXXX       XXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXX   XXXXXXXXX   XXXXXXXXXX XXXXXXXXX  XXXXXXXXXX  XXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXX   XXXXXXXXX   XXXXXXXXXX XXXXXXXXX  XXXXXXXXXX  XXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXX   XXXXXXXXX   XXXXXXXXXX XXXXXXXXX  XXXXXXXXXX  XXXXXXXXXXXX',
  ],
]
